### ISSUE TITLE
Stream Stuttering with Big Buck Bunny Movie

### ISSUE THREAD

**Issue by authenticate** [deepch/RTSPtoWebRTC#121]
Hi,

The Big Buck Bunny stream listed in the sample code (rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov) is stuttering during playback.  I viewed the stream using the RTSPtoWebRTC project with Chrome.

If I view rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov in VLC, it appears to play fine.

Thank you.

**Comment by deepch** [comment]
webrtc work only pcm codec alaw or ulaw

**Comment by authenticate** [comment]
Thank you.

**Comment by d21d3q** [comment]
### related to bunny video:

shouldn't it work without audio then?  

with
```
    "bunny": {
      "on_demand": false,
      "disable_audio": true,
      "url": "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
    }
```
it still stutters, and frame rate (`about:webrtc`) is quite low.
![image](https://user-images.githubusercontent.com/490844/157408589-0138eefb-055d-452f-9dee-ecdfbd1048e1.png)

### related to different video:

I was testing it with video from [here](https://file-examples.com/index.php/sample-video-files/sample-mp4-files/) (1920x1080 one), transcoded with: 
```
 ffmpeg -i test.mp4 -c:v libx264 -an  test_.mp4
```
and I have also been observing stuttering (and low frame rate in `about:webrtc`). But I noticed that frame rate changes if I reencode video with different key frame interval, so that having key frame every one frame makes it smooth. 
```
 ffmpeg -i test.mp4 -c:v libx264 -an -x264-params keyint=1:scenecut=0 test_.mp4
```

I've also added some tracing [here](https://github.com/deepch/RTSPtoWebRTC/blob/f4bc2f27cb9c085cee9c7d06cad9c43b8754d50c/http.go#L147) to see what is being sent (whether frames are dropped or something), and I observed negative frame durations. 

for keyframe on each frame, 
```
2022/03/09 10:12:10 videoStart
2022/03/09 10:12:10 WritePacket, IsKeyFrame: true Duration: 33ms
2022/03/09 10:12:10 videoStart
2022/03/09 10:12:10 WritePacket, IsKeyFrame: true Duration: 33ms
```

for "auto" keyframes:
```
2022/03/09 10:14:16 videoStart
2022/03/09 10:14:16 WritePacket, IsKeyFrame: true Duration: 33ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: 133ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: -66ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: -33ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: 66ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: 166ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: -66ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: -33ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: 66ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: 166ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: -66ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: -33ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: 66ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: 166ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: -66ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: -33ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: 66ms
2022/03/09 10:14:16 WritePacket, IsKeyFrame: false Duration: 166ms
```

I didn't dig deeper yet, but those negative durations seem suspicious to me.

**Comment by deepch** [comment]
try now

**Comment by deepch** [comment]
You know it looks like some kind of joke, he shouldn't jump like that.

**Comment by d21d3q** [comment]
Maybe it is also problem with `ffmpeg version 4.2.4-1ubuntu0.1`.

Streaming
```
 ffmpeg -re -stream_loop -1 -i test_.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:8554/live 
```
to rstp-simple-server
```
docker run --rm -it -p 8554:8554 aler9/rtsp-simple-server
```
produces non monotonous timestamps:
```
2022/03/10 13:32:26 seq: 4303 tmstp: 2676226906 duration: 66ms
2022/03/10 13:32:26 seq: 4308 tmstp: 2676235906 duration: -66ms
2022/03/10 13:32:26 seq: 4309 tmstp: 2676232906 duration: -33ms
2022/03/10 13:32:26 seq: 4310 tmstp: 2676238906 duration: 66ms
2022/03/10 13:32:26 seq: 4315 tmstp: 2676247906 duration: -66ms
2022/03/10 13:32:26 seq: 4316 tmstp: 2676244906 duration: -33ms
2022/03/10 13:32:26 seq: 4317 tmstp: 2676250906 duration: 66ms
2022/03/10 13:32:26 seq: 4322 tmstp: 2676259906 duration: -66ms
2022/03/10 13:32:26 seq: 4323 tmstp: 2676256906 duration: -33ms
2022/03/10 13:32:26 seq: 4324 tmstp: 2676262906 duration: 66ms
2022/03/10 13:32:26 seq: 4329 tmstp: 2676271906 duration: -66ms
2022/03/10 13:32:26 seq: 4330 tmstp: 2676268906 duration: -33ms
2022/03/10 13:32:26 seq: 4331 tmstp: 2676274906 duration: 66ms
```
above is trace from `RTSPtoWebRTC` but it is not rstp server manglign them - I can observe it in wireshark.

Another thing is that as OP I can play rstp stream smoothly in VLC what would mean that it doesn't care about RTP timestamps however webrtc does. Maybe `av.Packet.Duration` could be extracted from content? 

I manged to play your stream smoothly, durations are positive, but it tends to freeze and continue around key frames (in browser). Can you observe such behavior? Or it is going smooth all the time?

https://user-images.githubusercontent.com/490844/157667971-c8195a2b-2d9e-433b-a0bc-9e671c003626.mp4

**Comment by deepch** [comment]
I can add static pts on config you need only set fps custom value

**Comment by d21d3q** [comment]
I would take it on hold. I don't need it for now and I'll try to get valid input.

**Comment by d21d3q** [comment]
I got into this issue on the beginning while trying to run it for the first time (treating Bunny as hello world stream).  
So that I will leave here info how to produce valid input stream that works (while Bunny and ffmpeg mess with timestamps)

Run [`rtsp-simple-server`](https://github.com/aler9/rtsp-simple-server):
```
docker run -p 8554:8554 -p 1935:1935 -e RTSP_PROTOCOLS=tcp aler9/rtsp-simple-server
```
Run [OBS](https://obsproject.com/) and make it stream to `rtmp://localhost:1935/live` and configure `RTSPtoWebRTC` to `rtsp://localhost:8554/live`.

**Comment by deepch** [comment]
I'm happy for you

ps. I hope you don't think all Russians are bad ;( 
I am also against the war.
