### ISSUE TITLE
startSession is not defined

### ISSUE THREAD

**Issue by ohuolo** [deepch/RTSPtoWebRTC#53]
Uncaught ReferenceError: startSession is not defined
where the function define?i found everwhere,can not find it.

**Comment by miguelrvs** [comment]
Happened the same here:
Apparently was caused because the video stream was not H.264 (it was configured as MJPEG).
After configuring the video coding to H.264 the problem was fixed. Also not all video sizes/framerates/bitrates are liked by de browser. You will have to do some experimentation finding working settings.
Look at: [Limitations](https://github.com/deepch/RTSPtoWebRTC/#limitations)
